Update build dashboard workflow and error handling.
This commits adds required branch name arguments for build
dashboard github action.
A fallback mechanism is added to make sure no orphan data locks
exist in case of error in data recorder script.

Closes #774

Signed-off-by: Shakti Suman <shaksuma@qti.qualcomm.com>

diff --git a/.github/workflows/BuildStatusDataRecorder/action.yaml b/.github/workflows/BuildStatusDataRecorder/action.yaml
--- a/.github/workflows/BuildStatusDataRecorder/action.yaml
+++ b/.github/workflows/BuildStatusDataRecorder/action.yaml
@@ -86,23 +86,46 @@ runs:
         # Record build status data for current workflow.
         echo "Proceeding with data recording..."
         cp ${DASH_DIR}/record_builds.py .
+        # Set +e to not immediately exit "run" step on failure.
+        set +e
         python record_builds.py --workflow ${{ inputs.workflow-name }} --${{ inputs.record-mode }} --${{ inputs.status }} --run-id ${{ inputs.run-id }} --arch ${{ inputs.arch-name }} --branch ${{ inputs.branch-name }}
-        cp build-status.db ${DASH_DIR}/
-        rm -f record_builds.py
-        echo "Removing ${{ inputs.workflow-name }} ${{ inputs.arch-name }} data lock."
-        rm -f data.lock
-        git add .
-        git commit -m "Add ${{ inputs.workflow-name }} ${{ inputs.arch-name }} build status data in DB"
-        # Keep trying until lock/conflicts are resolved and build data is pushed successfully.
-        until git push -f origin HEAD:refs/heads/dashboard; do
-          sleep 5
-          check_lock
-          git fetch --all
-          git reset --hard origin/dashboard
-          cp -f ${DASH_DIR}/build-status.db .
+        EXITCODE=$?
+        if [ "$EXITCODE" -ne 0 ]; then
+           echo "Build Data Recording Failed!"
+           echo "Removing Data Lock and Cleaning Up..."
+           rm -f record_builds.py
+           rm -f data.lock
+           git add .
+           git commit -m "Removing ${{ inputs.workflow-name }} ${{ inputs.arch-name }} data lock."
+           until git push -f origin HEAD:refs/heads/dashboard; do
+            sleep 5
+            check_lock
+            git fetch --all
+            git reset --hard origin/dashboard
+            rm -f data.lock
+            git add .
+            git commit -m "Removing ${{ inputs.workflow-name }} ${{ inputs.arch-name }} data lock."
+          done
+          rm -rf ${DASH_DIR}
+          git checkout -
+        else
+          cp build-status.db ${DASH_DIR}/
+          rm -f record_builds.py
+          echo "Removing ${{ inputs.workflow-name }} ${{ inputs.arch-name }} data lock."
           rm -f data.lock
           git add .
-          git commit -m "Add ${{ inputs.workflow-name }} ${{ matrix.arch.name }} build status data in DB"
-        done
-        rm -rf ${DASH_DIR}
-        git checkout -
+          git commit -m "Add ${{ inputs.workflow-name }} ${{ inputs.arch-name }} build status data in DB"
+          # Keep trying until lock/conflicts are resolved and build data is pushed successfully.
+          until git push -f origin HEAD:refs/heads/dashboard; do
+            sleep 5
+            check_lock
+            git fetch --all
+            git reset --hard origin/dashboard
+            cp -f ${DASH_DIR}/build-status.db .
+            rm -f data.lock
+            git add .
+            git commit -m "Add ${{ inputs.workflow-name }} ${{ matrix.arch.name }} build status data in DB"
+          done
+          rm -rf ${DASH_DIR}
+          git checkout -
+        fi
